const rows = [
  {
    id: "ABC123",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Alice Johnson",
    designation: "CTO",
    action: "UPDATE",
    type: "Web",
    environment: "Development",
    timestamp: "1 day ago",
  },
  {
    id: "XYZ456",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Bob Smith",
    designation: "Lead Designer",
    action: "UPDATE",
    type: "Content",
    environment: "Production",
    timestamp: "3 days ago",
  },
  {
    id: "DEF789",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Eva Davis",
    designation: "Marketing Manager",
    action: "UNPUBLISH",
    type: "Marketing",
    environment: "Production",
    timestamp: "4 days ago",
  },
  {
    id: "LMN012",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Charlie Brown",
    designation: "Software Engineer",
    action: "PUBLISH",
    type: "Development",
    environment: "Testing",
    timestamp: "5 days ago",
  },
  {
    id: "PQR345",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Grace Lee",
    designation: "HR Manager",
    action: "CREATE",
    type: "HR",
    environment: "Production",
    timestamp: "6 days ago",
  },
  {
    id: "GHI678",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Oliver Taylor",
    designation: "Sales Representative",
    action: "DELETE",
    type: "Sales",
    environment: "Production",
    timestamp: "1 week ago",
  },
  {
    id: "JKL901",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Sophia Hall",
    designation: "Product Manager",
    action: "CREATE",
    type: "Product",
    environment: "Production",
    timestamp: "2 weeks ago",
  },
  {
    id: "MNO234",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Daniel White",
    designation: "Finance Director",
    action: "CREATE",
    type: "Finance",
    environment: "Production",
    timestamp: "3 weeks ago",
  },
  {
    id: "UVW567",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Ava Turner",
    designation: "Operations Manager",
    action: "DELETE",
    type: "Operations",
    environment: "Production",
    timestamp: "4 weeks ago",
  },
  {
    id: "XYZ890",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "John Doe",
    designation: "CEO",
    action: "UPDATE",
    type: "Project",
    environment: "Production",
    timestamp: "2 days ago",
  },
  {
    id: "XYZ890",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "John Doe",
    designation: "CEO",
    action: "UPDATE",
    type: "Project",
    environment: "Production",
    timestamp: "2 days ago",
  },
  {
    id: "XYZ890",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "John Doe",
    designation: "CEO",
    action: "UPDATE",
    type: "Project",
    environment: "Production",
    timestamp: "2 days ago",
  },
  {
    id: "XYZ890",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "John Doe",
    designation: "CEO",
    action: "UPDATE",
    type: "Project",
    environment: "Production",
    timestamp: "2 days ago",
  },
  {
    id: "XYZ890",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "John Doe",
    designation: "CEO",
    action: "UPDATE",
    type: "Project",
    environment: "Production",
    timestamp: "2 days ago",
  },
  {
    id: "XYZ890",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "John Doe",
    designation: "CEO",
    action: "UPDATE",
    type: "Project",
    environment: "Production",
    timestamp: "2 days ago",
  },
  {
    id: "XYZ890",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "John Doe",
    designation: "CEO",
    action: "UPDATE",
    type: "Project",
    environment: "Production",
    timestamp: "2 days ago",
  },
  {
    id: "XYZ890",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "John Doe",
    designation: "CEO",
    action: "UPDATE",
    type: "Project",
    environment: "Production",
    timestamp: "2 days ago",
  },
  {
    id: "XYZ890",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "John Doe",
    designation: "CEO",
    action: "UPDATE",
    type: "Project",
    environment: "Production",
    timestamp: "2 days ago",
  },
  {
    id: "XYZ890",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "John Doe",
    designation: "CEO",
    action: "UPDATE",
    type: "Project",
    environment: "Production",
    timestamp: "2 days ago",
  },
  {
    id: "XYZ890",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "John Doe",
    designation: "CEO",
    action: "UPDATE",
    type: "Project",
    environment: "Production",
    timestamp: "2 days ago",
  },
  {
    id: "XYZ890",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "John Doe",
    designation: "CEO",
    action: "UPDATE",
    type: "Project",
    environment: "Production",
    timestamp: "2 days ago",
  },
  {
    id: "XYZ890",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "John Doe",
    designation: "CEO",
    action: "UPDATE",
    type: "Project",
    environment: "Production",
    timestamp: "2 days ago",
  },
  {
    id: "XYZ890",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "John Doe",
    designation: "CEO",
    action: "UPDATE",
    type: "Project",
    environment: "Production",
    timestamp: "2 days ago",
  },
  {
    id: "XYZ890",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "John Doe",
    designation: "CEO",
    action: "UPDATE",
    type: "Project",
    environment: "Production",
    timestamp: "2 days ago",
  },
  {
    id: "XYZ890",
    image: "https://www.w3schools.com/howto/img_avatar.png",
    name: "John Doe",
    designation: "CEO",
    action: "UPDATE",
    type: "Project",
    environment: "Production",
    timestamp: "2 days ago",
  },
];

export default rows;